name: Bug Report
description: Report an issue with the knowledge base (broken links, formatting, incorrect content)
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Broken link
        - Formatting issue
        - Incorrect content
        - Missing content
        - Build/deployment failure
        - Skill malfunction
        - Other
    validations:
      required: true

  - type: input
    id: file-path
    attributes:
      label: Affected File(s)
      description: Path to the affected file(s)
      placeholder: e.g., policies/hr/pto-policy.md

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the issue?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots
